// 외부 배포용 Tailwind preset
// 이 파일은 자동 생성됩니다. src/theme/light.ts를 수정한 후
// pnpm generate:preset을 실행하여 재생성하세요.

/** @type {import('tailwindcss').Config} */
const config = {
  prefix: 'wg-', // @wiid-get/design-system의 약자
  // content: [], // 배포용이므로 content는 비워둠 (사용자가 직접 정함)
  theme: {
    extend: {
      colors: {
        primary: {
          50: 'rgb(var(--wg-color-primary-50) / <alpha-value>)',
          100: 'rgb(var(--wg-color-primary-100) / <alpha-value>)',
          200: 'rgb(var(--wg-color-primary-200) / <alpha-value>)',
          300: 'rgb(var(--wg-color-primary-300) / <alpha-value>)',
          400: 'rgb(var(--wg-color-primary-400) / <alpha-value>)',
          500: 'rgb(var(--wg-color-primary-500) / <alpha-value>)',
          600: 'rgb(var(--wg-color-primary-600) / <alpha-value>)',
          700: 'rgb(var(--wg-color-primary-700) / <alpha-value>)',
          800: 'rgb(var(--wg-color-primary-800) / <alpha-value>)',
          900: 'rgb(var(--wg-color-primary-900) / <alpha-value>)',
        },
        secondary: {
          50: 'rgb(var(--wg-color-secondary-50) / <alpha-value>)',
          100: 'rgb(var(--wg-color-secondary-100) / <alpha-value>)',
          200: 'rgb(var(--wg-color-secondary-200) / <alpha-value>)',
          300: 'rgb(var(--wg-color-secondary-300) / <alpha-value>)',
          400: 'rgb(var(--wg-color-secondary-400) / <alpha-value>)',
          500: 'rgb(var(--wg-color-secondary-500) / <alpha-value>)',
          600: 'rgb(var(--wg-color-secondary-600) / <alpha-value>)',
          700: 'rgb(var(--wg-color-secondary-700) / <alpha-value>)',
          800: 'rgb(var(--wg-color-secondary-800) / <alpha-value>)',
          900: 'rgb(var(--wg-color-secondary-900) / <alpha-value>)',
        },
        tertiary: {
          50: 'rgb(var(--wg-color-tertiary-50) / <alpha-value>)',
          100: 'rgb(var(--wg-color-tertiary-100) / <alpha-value>)',
          200: 'rgb(var(--wg-color-tertiary-200) / <alpha-value>)',
          300: 'rgb(var(--wg-color-tertiary-300) / <alpha-value>)',
          400: 'rgb(var(--wg-color-tertiary-400) / <alpha-value>)',
          500: 'rgb(var(--wg-color-tertiary-500) / <alpha-value>)',
          600: 'rgb(var(--wg-color-tertiary-600) / <alpha-value>)',
          700: 'rgb(var(--wg-color-tertiary-700) / <alpha-value>)',
          800: 'rgb(var(--wg-color-tertiary-800) / <alpha-value>)',
          900: 'rgb(var(--wg-color-tertiary-900) / <alpha-value>)',
        },
        accent: {
          50: 'rgb(var(--wg-color-accent-50) / <alpha-value>)',
          100: 'rgb(var(--wg-color-accent-100) / <alpha-value>)',
          200: 'rgb(var(--wg-color-accent-200) / <alpha-value>)',
          300: 'rgb(var(--wg-color-accent-300) / <alpha-value>)',
          400: 'rgb(var(--wg-color-accent-400) / <alpha-value>)',
          500: 'rgb(var(--wg-color-accent-500) / <alpha-value>)',
          600: 'rgb(var(--wg-color-accent-600) / <alpha-value>)',
          700: 'rgb(var(--wg-color-accent-700) / <alpha-value>)',
          800: 'rgb(var(--wg-color-accent-800) / <alpha-value>)',
          900: 'rgb(var(--wg-color-accent-900) / <alpha-value>)',
        },
        success: {
          50: 'rgb(var(--wg-color-success-50) / <alpha-value>)',
          100: 'rgb(var(--wg-color-success-100) / <alpha-value>)',
          500: 'rgb(var(--wg-color-success-500) / <alpha-value>)',
          600: 'rgb(var(--wg-color-success-600) / <alpha-value>)',
          700: 'rgb(var(--wg-color-success-700) / <alpha-value>)',
        },
        warning: {
          50: 'rgb(var(--wg-color-warning-50) / <alpha-value>)',
          100: 'rgb(var(--wg-color-warning-100) / <alpha-value>)',
          500: 'rgb(var(--wg-color-warning-500) / <alpha-value>)',
          600: 'rgb(var(--wg-color-warning-600) / <alpha-value>)',
          700: 'rgb(var(--wg-color-warning-700) / <alpha-value>)',
        },
        error: {
          50: 'rgb(var(--wg-color-error-50) / <alpha-value>)',
          100: 'rgb(var(--wg-color-error-100) / <alpha-value>)',
          500: 'rgb(var(--wg-color-error-500) / <alpha-value>)',
          600: 'rgb(var(--wg-color-error-600) / <alpha-value>)',
          700: 'rgb(var(--wg-color-error-700) / <alpha-value>)',
        },
        info: {
          50: 'rgb(var(--wg-color-info-50) / <alpha-value>)',
          100: 'rgb(var(--wg-color-info-100) / <alpha-value>)',
          500: 'rgb(var(--wg-color-info-500) / <alpha-value>)',
          600: 'rgb(var(--wg-color-info-600) / <alpha-value>)',
          700: 'rgb(var(--wg-color-info-700) / <alpha-value>)',
        },
        neutral: {
          50: 'rgb(var(--wg-color-neutral-50) / <alpha-value>)',
          100: 'rgb(var(--wg-color-neutral-100) / <alpha-value>)',
          200: 'rgb(var(--wg-color-neutral-200) / <alpha-value>)',
          300: 'rgb(var(--wg-color-neutral-300) / <alpha-value>)',
          400: 'rgb(var(--wg-color-neutral-400) / <alpha-value>)',
          500: 'rgb(var(--wg-color-neutral-500) / <alpha-value>)',
          600: 'rgb(var(--wg-color-neutral-600) / <alpha-value>)',
          700: 'rgb(var(--wg-color-neutral-700) / <alpha-value>)',
          800: 'rgb(var(--wg-color-neutral-800) / <alpha-value>)',
          900: 'rgb(var(--wg-color-neutral-900) / <alpha-value>)',
        },
        background: 'rgb(var(--wg-color-background) / <alpha-value>)',
        foreground: 'rgb(var(--wg-color-foreground) / <alpha-value>)',
        muted: {
          DEFAULT: 'rgb(var(--wg-color-muted) / <alpha-value>)',
          foreground: 'rgb(var(--wg-color-muted-foreground) / <alpha-value>)',
        },
        border: 'rgb(var(--wg-color-border) / <alpha-value>)',
        ring: 'rgb(var(--wg-color-ring) / <alpha-value>)',
      },
      spacing: {
        0: 'var(--wg-spacing-0)',
        1: 'var(--wg-spacing-1)',
        2: 'var(--wg-spacing-2)',
        3: 'var(--wg-spacing-3)',
        4: 'var(--wg-spacing-4)',
        5: 'var(--wg-spacing-5)',
        6: 'var(--wg-spacing-6)',
        8: 'var(--wg-spacing-8)',
        10: 'var(--wg-spacing-10)',
        12: 'var(--wg-spacing-12)',
        16: 'var(--wg-spacing-16)',
        20: 'var(--wg-spacing-20)',
        24: 'var(--wg-spacing-24)',
        32: 'var(--wg-spacing-32)',
        40: 'var(--wg-spacing-40)',
        48: 'var(--wg-spacing-48)',
        64: 'var(--wg-spacing-64)',
      },
      borderRadius: {
        none: 'var(--wg-border-radius-none)',
        sm: 'var(--wg-border-radius-sm)',
        DEFAULT: 'var(--wg-border-radius-md)',
        lg: 'var(--wg-border-radius-lg)',
        xl: 'var(--wg-border-radius-xl)',
        full: 'var(--wg-border-radius-full)',
      },
      boxShadow: {
        sm: 'var(--wg-shadow-sm)',
        DEFAULT: 'var(--wg-shadow-md)',
        lg: 'var(--wg-shadow-lg)',
        xl: 'var(--wg-shadow-xl)',
      },
      backgroundImage: {
        'shallow-beach-to-deep-sea': 'var(--wg-gradient-shallow-beach-to-deep-sea)',
        'shallow-beach-to-algae': 'var(--wg-gradient-shallow-beach-to-algae)',
        'shallow-beach-to-sand': 'var(--wg-gradient-shallow-beach-to-sand)',
        'shallow-beach-to-sunset': 'var(--wg-gradient-shallow-beach-to-sunset)',
        'shallow-beach-to-golden-light': 'var(--wg-gradient-shallow-beach-to-golden-light)',
        'deep-sea-to-shallow-beach': 'var(--wg-gradient-deep-sea-to-shallow-beach)',
        'deep-sea-to-algae': 'var(--wg-gradient-deep-sea-to-algae)',
        'deep-sea-to-sand': 'var(--wg-gradient-deep-sea-to-sand)',
        'deep-sea-to-sunset': 'var(--wg-gradient-deep-sea-to-sunset)',
        'deep-sea-to-golden-light': 'var(--wg-gradient-deep-sea-to-golden-light)',
        'algae-to-shallow-beach': 'var(--wg-gradient-algae-to-shallow-beach)',
        'algae-to-deep-sea': 'var(--wg-gradient-algae-to-deep-sea)',
        'algae-to-sand': 'var(--wg-gradient-algae-to-sand)',
        'algae-to-sunset': 'var(--wg-gradient-algae-to-sunset)',
        'algae-to-golden-light': 'var(--wg-gradient-algae-to-golden-light)',
        'sand-to-shallow-beach': 'var(--wg-gradient-sand-to-shallow-beach)',
        'sand-to-deep-sea': 'var(--wg-gradient-sand-to-deep-sea)',
        'sand-to-algae': 'var(--wg-gradient-sand-to-algae)',
        'sand-to-sunset': 'var(--wg-gradient-sand-to-sunset)',
        'sand-to-golden-light': 'var(--wg-gradient-sand-to-golden-light)',
        'sunset-to-shallow-beach': 'var(--wg-gradient-sunset-to-shallow-beach)',
        'sunset-to-deep-sea': 'var(--wg-gradient-sunset-to-deep-sea)',
        'sunset-to-algae': 'var(--wg-gradient-sunset-to-algae)',
        'sunset-to-sand': 'var(--wg-gradient-sunset-to-sand)',
        'sunset-to-golden-light': 'var(--wg-gradient-sunset-to-golden-light)',
        'golden-light-to-shallow-beach': 'var(--wg-gradient-golden-light-to-shallow-beach)',
        'golden-light-to-deep-sea': 'var(--wg-gradient-golden-light-to-deep-sea)',
        'golden-light-to-algae': 'var(--wg-gradient-golden-light-to-algae)',
        'golden-light-to-sand': 'var(--wg-gradient-golden-light-to-sand)',
        'golden-light-to-sunset': 'var(--wg-gradient-golden-light-to-sunset)',
      },
    },
  },
  plugins: [],
}

export default config
